name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX document
        run: |
          pdflatex ./src/Deckblatt.tex
          pdflatex ./src/Deckblatt.tex  # Zweimal ausführen für Referenzen

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Deckblatt
          path: Deckblatt.pdf

  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Deckblatt
          path: Deckblatt.pdf

      - name: Unzip artifact
        run: unzip Deckblatt.zip -d output_directory

      - name: Upload PDF
        run: |
          git config --local user.email "wilfried.ifland@example.com"
          git config --local user.name "iwilfried"
          git add output_directory/Deckblatt.pdf
          git commit -m "Add generated PDF"
          git push
