name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository klonen
        uses: actions/checkout@v4
      
        
      - name: LaTeX installieren
        run: sudo apt-get install texlive-full
        
      - name: LaTeX kompilieren
        run: pdflatex -output-directory=output src/Deckblatt.tex
