name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX document
        run: |
          pdflatex ./src/Deckblatt.tex
          pdflatex ./src/Deckblatt.tex  # Zweimal ausführen für Referenzen

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: Deckblatt
          path: Deckblatt.pdf

