name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository klonen
        uses: actions/checkout@v4
      
        
      - name: LaTeX installieren
        run: sudo apt-get install texlive-full
        
      - name: Verzeichnisstruktur anzeigen
        run: ls -R

      - name: Ausgabeverzeichnis erstellen und Berechtigungen setzen
        run: |
           mkdir -p output
           chmod 777 output

      - name: Deckblatt kompilieren
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error -output-directory=$PWD/output $PWD/src/Deckblatt.tex
          working-directory: ${{ github.workspace }}

      - name: Inhalt des Ausgabeverzeichnisses anzeigen
        run: ls -l output

      - name: Log-Datei anzeigen (falls vorhanden)
        run: cat output/Deckblatt.log
        if: failure()
