name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository klonen
        uses: actions/checkout@v4
      
        
      - name: LaTeX installieren
        run: sudo apt-get install texlive-full
        
      - name: Verzeichnisstruktur anzeigen
        run: ls -R

      - name: Ausgabeverzeichnis erstellen und Berechtigungen setzen
        run: mkdir -p output
        

      - name: Deckblatt kompilieren
        working-directory: ${{ github.workspace }}

        run: pdflatex -interaction=nonstopmode -halt-on-error -output-directory=$PWD/output $PWD/src/Deckblatt.tex

      - name: Artefakt hochladen
        uses: actions/upload-artifact@v2
        with:
          name: Deckblatt
          path: output/Deckblatt.pdf
