name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install LaTeX
        run: sudo apt-get install texlive-full
      - name: Compile LaTeX
        run: pdflatex src/Deckblatt.tex
